---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.elasticsearch.name | default "elasticsearch" }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.elasticsearch.name | default "elasticsearch" }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name  }}
      ports:
        - protocol: TCP
          port: {{ .Values.elasticsearch.port }}

