apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
  clusterIP: None