apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
  selector:
    app: elasticsearch
