apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  labels:
    app: {{ include "city-population-app.name" . }}
    chart: {{ include "city-population-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  url: {{ .Values.elasticsearch.url | b64enc | quote }}
  username: {{ .Values.elasticsearch.username | b64enc | quote }}
  password: {{ .Values.elasticsearch.password | b64enc | quote }}