apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  url: {{ (print "http://" .Values.elasticsearch.name ":" .Values.elasticsearch.port) | b64enc | quote }}
  username: {{ .Values.elasticsearch.username | b64enc | quote }}
  password: {{ .Values.elasticsearch.password | b64enc | quote }}